services:
  motive-solutions-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartifly-smf-app
    restart: always
    ports:
      - "127.0.0.1:3063:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
